name: ente_crypto_cross_check_adapter
description: CryptoApi implementation that cross-checks dart and rust crypto.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  ente_crypto_api:
    path: ../ente_crypto_api
  ente_crypto_dart_adapter:
    path: ../ente_crypto_dart_adapter
  ente_crypto_rust_adapter:
    path: ../ente_crypto_rust_adapter
  ente_rust:
    path: ../rust
  logging: ^1.3.0

dev_dependencies:
  lints: ^3.0.0
