name: ente_crypto_rust_adapter
description: CryptoApi implementation backed by ente_rust.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  ente_crypto_api:
    path: ../ente_crypto_api
  ente_rust:
    path: ../rust

dev_dependencies:
  lints: ^3.0.0
