name: ensu
description: End-to-end encrypted chat app powered by Ente
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  adaptive_theme: ^3.1.0
  app_links: ^6.4.1
  archive: ^4.0.7
  collection: ^1.18.0
  connectivity_plus: ^6.0.5
  dio: ^5.8.0+1
  email_validator: ^3.0.0
  ente_accounts:
    path: ../../packages/accounts
  ente_base:
    path: ../../packages/base
  ente_configuration:
    path: ../../packages/configuration
  ente_crypto_api:
    path: ../../packages/ente_crypto_api
  ente_crypto_cross_check_adapter:
    path: ../../packages/ente_crypto_cross_check_adapter
  ente_crypto_dart:
    git:
      url: https://github.com/ente-io/ente_crypto_dart.git
  ente_crypto_dart_adapter:
    path: ../../packages/ente_crypto_dart_adapter
  ente_crypto_rust_adapter:
    path: ../../packages/ente_crypto_rust_adapter
  ente_events:
    path: ../../packages/events
  ente_logging:
    path: ../../packages/logging
  ente_network:
    path: ../../packages/network
  ente_rust:
    path: ../../packages/rust
  ente_strings:
    path: ../../packages/strings
  ente_ui:
    path: ../../packages/ui
  ente_utils:
    path: ../../packages/utils
  event_bus: ^2.0.0
  file_picker: ^10.3.2
  fllama:
    path: /Users/prateek/Documents/gits/fllama
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  flutter_markdown: ^0.7.4
  markdown: ^7.3.0
  flutter_rust_bridge: 2.11.1
  flutter_secure_storage: 9.0.0
  google_fonts: ^6.3.2
  google_generative_ai: ^0.4.7
  http: ^1.6.0
  intl: ^0.20.2
  lucide_icons: ^0.257.0
  llama_cpp_dart: ^0.1.2+1
  logging: ^1.0.1
  open_file: ^3.5.10
  path: ^1.8.3
  path_provider: ^2.0.11
  pointycastle: ^3.7.3
  shared_preferences: ^2.0.5
  sqlcipher_flutter_libs: ^0.6.4
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.0+4
  sqflite_sqlcipher: ^3.3.0
  sqlite3: ^2.4.3
  syncfusion_flutter_pdf: ^29.1.38
  url_launcher: ^6.3.2
  uuid: ^4.2.2
  xml: ^6.3.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lints: ^5.1.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Medium.ttf
        - asset: fonts/Inter-Light.ttf
        - asset: fonts/Inter-SemiBold.ttf
        - asset: fonts/Inter-Bold.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#F8F5F0"
  adaptive_icon_foreground: "assets/icon.png"
